=== Saul902/LenguajeMarcas/Validacion/ejercicio5.dtd
<!ELEMENT cv (nombre,apellidos,informacion_contacto,sobre_mi,experiencia_trabajo,educacion,idiomas)>
<!ELEMENT informacion_contacto (numero_telefono,correo,fecha_nacimiento)>
<!ELEMENT experiencia_trabajo (trabajo*)>
<!ELEMENT trabajo (nombre_trabajo,ubicacion_trabajo,fecha_trabajo)>
<!ELEMENT educacion (centro*)>
<!ELEMENT centro (nombre_centro,curso,ubicacion_centro,fecha_centro)>
<!ELEMENT idiomas (idioma+)>
<!ELEMENT idioma (nombre_idioma,nivel)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT numero_telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT sobre_mi (#PCDATA)>
<!ELEMENT nombre_trabajo (#PCDATA)>
<!ELEMENT ubicacion_trabajo (#PCDATA)>
<!ELEMENT fecha_trabajo (#PCDATA)>
<!ELEMENT nombre_centro (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT ubicacion_centro (#PCDATA)>
<!ELEMENT fecha_centro (#PCDATA)>
<!ELEMENT nombre_idioma (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>

<!ATTLIST cv lang (es|en) #REQUIRED>

=== Saul902/LenguajeMarcas/Validacion/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "ejercicio5.dtd">
    <cv lang="es">
        <nombre>Saul</nombre>
        <apellidos>Ruiz</apellidos>
        <informacion_contacto>
            <numero_telefono>+34 653 72 73 12</numero_telefono>
            <correo>saul@gmail.com</correo>
            <fecha_nacimiento>25/01/01</fecha_nacimiento>
        </informacion_contacto>
        <sobre_mi>Me considero una persona responsable, eficiente, trabajadora y con ganas de aprender.</sobre_mi>
        <experiencia_trabajo>
            <trabajo>
                <nombre_trabajo>1trabajo</nombre_trabajo>
                <ubicacion_trabajo>ubicacion</ubicacion_trabajo>
                <fecha_trabajo>2022</fecha_trabajo>
            </trabajo>
        </experiencia_trabajo>
        <educacion>
            <centro>
                <nombre_centro>centro</nombre_centro>
                <curso>curso</curso>
                <ubicacion_centro>ubicacion</ubicacion_centro>
                <fecha_centro>2021-2023</fecha_centro>
            </centro>
            <centro>
                <nombre_centro>centro</nombre_centro>
                <curso>curso</curso>
                <ubicacion_centro>ubicacion</ubicacion_centro>
                <fecha_centro>2015-2020</fecha_centro>
            </centro>
        </educacion>
        <idiomas>
            <idioma>
                <nombre_idioma>Inglés</nombre_idioma>
                <nivel>Fluido</nivel>
            </idioma>
            <idioma>
                <nombre_idioma>Español</nombre_idioma>
                <nivel>Nativo</nivel>
            </idioma>
            <idioma>
                <nombre_idioma>Valenciano</nombre_idioma>
                <nivel>Nativo</nivel>
            </idioma>
        </idiomas>
    </cv>
