=== Saul902/LenguajeMarcas/Validacion/ejercicio2.dtd
<!ELEMENT minecraftItems (item+)>
<!ELEMENT item (name,damage?,description,materials?,enchantments?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT rarity (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT materials (material+)>
<!ELEMENT material (#PCDATA)>
<!ELEMENT enchantments (enchantment+)>
<!ELEMENT enchantment (#PCDATA)>

<!ATTLIST minecraftItems lang (es|en) #REQUIRED>
<!ATTLIST item id ID #REQUIRED
    crafteable (true|false) #REQUIRED
    enchantable (true|false) #REQUIRED
    type (arma|herramienta|bloque|mineral|consumible) #REQUIRED
    rarity (comun|raro|epico|legendario) #REQUIRED>

=== Saul902/LenguajeMarcas/Validacion/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "ejercicio2.dtd">
    <minecraftItems lang="es">
        <item id="id1" crafteable="false" enchantable="false" type="bloque" rarity="comun">
            <name>Bloque de tierra</name>
            <damage>10</damage>
            <description>Un bloque de tierra para plantar cultivos</description>
        </item>
        <item id="id2" crafteable="true" enchantable="true" type="arma" rarity="legendario">
            <name>Espada de diamante</name>
            <damage>350</damage>
            <description>Una espada hecha de diamantes para matar mobs hostiles</description>
            <materials>
                <material>diamante</material>
                <material>diamante</material>
                <material>palo de madera</material>
            </materials>
            <enchantments>
                <enchantment>Irrompibilidad</enchantment>
                <enchantment>Reparacion</enchantment>
                <enchantment>Golpeo</enchantment>
            </enchantments>
        </item>
        <item id="id3" crafteable="false" enchantable="true" type="mineral" rarity="legendario">
            <name>Diamante</name>
            <description>El mineral mas preciado de Minecraft</description>
            <enchantments>
                <enchantment>Durabilidad</enchantment>
            </enchantments>
        </item>
        <item id="id4" crafteable="true" enchantable="true" type="herramienta" rarity="raro">
            <name>Pico de hierro</name>
            <damage>30</damage>
            <description>Pico de hierro que puede picar diamantes</description>
            <materials>
                <material>hierro</material>
                <material>hierro</material>
                <material>hierro</material>
                <material>palo de madera</material>
                <material>palo de madera</material>
            </materials>
            <enchantments>
                <enchantment>Eficiencia</enchantment>
                <enchantment>Irrompibilidad</enchantment>
                <enchantment>Reparacion</enchantment>
            </enchantments>
        </item>
        <item id="id5" crafteable="false" enchantable="false" type="consumible" rarity="epico">
            <name>Ender pearl</name>
            <damage>10</damage>
            <description>Una perla que cuando la tiras te teletransporta a donde aterrice</description>
        </item>
        <item id="id6" crafteable="false" enchantable="true" type="arma" rarity="comun">
            <name>Palo de madera</name>
            <damage>10</damage>
            <description>Un palo para todo tipo de crafteos</description>
            <enchantments>
                <enchantment>Empuje</enchantment>
                <enchantment>Irrompibilidad</enchantment>
                <enchantment>Golpeo</enchantment>
            </enchantments>
        </item>
    </minecraftItems>
